activemq:
    broker:
      url: "tcp://0.0.0.0:61616"
    user:
    password:
    client:
      timeout: 5000

destination:
    queue:
      hello:    hello.queue
      request:  request.queue
      response: response.queue

springdoc:
  swagger-ui:
    path: /apidoc